app_a/urls.py
# app_a urlpatterns

from django.urls import path

from . import views

app_name = 'app_a'

urlpatterns = [
    # index
    path('', views.index, name='index'),
    path('sec', views.sec, name='sec'),
    path('topics/', views.topics, name='topics'),
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
    
]

app_b/urls.py
from django.urls import path
from . import views

pro_a/urls.py
from django.contrib import admin
from django.urls import path,include

from app_a.views import sec
from app_b.views import fir
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('app_a.urls')),
    path('users/',include('users.urls')),
     

    path('appb/',fir,name='fir'), 



]

users/urls.py
from django.urls import path, include
from . import views
app_name='users'
urlpatterns=[
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

app_a/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Topic (models.Model):
    text= models.CharField(max_length=200)
    
    date_added =models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.text    

class Entry(models.Model):
    topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    class Meta():
        verbose_name_plural='entries'
    def __str__(self):
        return self.text[:50]+'...'
    #   return f"{self.text[:50]}..."

app_b/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

app_a/forms.py
from django import forms
from .models import Entry, Topic


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text',]
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry

        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

app_a/views.py
from http.client import ImproperConnectionState
from django.shortcuts import render, redirect
from .models import Topic,Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    return render(request, 'app_a/index.html')


def sec(request):
    return render(request, 'app_a/sec.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'app_a/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner!=request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'app_a/topic.html', context)
@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:

        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return redirect('app_a:topics')
    context = {'form': form}
    return render(request, 'app_a/new_topic.html', context)


#def new_topic(request):
    if request.method == 'POST':
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_a:topics')
    else:
        form = TopicForm()
        context = {'form': form}
        return render(request, 'app_a/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('app_a:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'app_a/new_entry.html', context)
@login_required
def edit_entry(request,entry_id):
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner !=request.user:
        raise Http404
    if request.method !='POST':
        form=EntryForm(instance=entry)
    else:
        form=EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_a:topic',topic_id=topic.id)
    context={'entry':entry,'topic':topic,'form':form}
    return render(request,'app_a/edit_entry.html',context)


    

app_b/views.py
from django.shortcuts import render

# Create your views here.
def fir(request):
    return render(request,'secfir.html')

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import  login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method !="POST":

        form= UserCreationForm()
    else:
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user= form.save()
        login(request,new_user)
        return redirect('app_a:index')
    context={'form':form}
    return render(request,'registration/register.html',context)

app_a/templates/app_a/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shring-to-fit=no">
    <title>Learning log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'app_a:index' %} ">Summertime Sadness</a>
        <button 
        class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nar mr-auto">
                <li class="nav-item">
                    <a href="{% url 'app_a:topics' %}" class="nav-link">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{user.username}}.</span>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
                    </li>
                {% else %}
                    </li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">Register</a>
                    </li> 
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Log in</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %} {% endblock page_header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>

    </main>
    
</body>
</html>

app_a/templates/app_a/bbase.html
<head>Summertime Sadness</head>
<p>
    <a href="{% url 'app_a:index' %}">Home page</a>
    <a href="{% url 'app_a:topics' %}">Topics</a>
    {% if user.is_authenticated %}
        hello, {{ request.user.username }}.
        <a href="{% url 'users:logout' %} ">Log out</a>
    {% else %} 
        <a href="{% url 'users:register' %}"> register </a>
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}

</p>
{% block content %} {% endblock content %}

app_a/templates/app_a/edit_entry.html
{% extends 'app_a/base.html' %}
{% block content %}
<p><a href="{% url 'app_a:topic' topic.id %}"> {{topic}} </a> 
</p>
<p>Edit entry:</p>
<form action="{% url 'app_a:edit_entry' entry.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button name="submit">Save changes</button>
</form>
{% endblock content %}

app_a/templates/app_a/index.html
{% extends "app_a/base.html" %}
{% block page_header %}
<div>
    <h1 class="display-3">Track your learning</h1>
    <p class="lead">Make your own Learning Log, and keep a list of the 
        topis you're learning about. Whenever you're learning about a topic,
        make an entry summarizing what you've learned.
    </p>
    <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Register &raquo;</a>
</div>
{% endblock page_header %}

app_a/templates/app_a/new_entry.html
{% extends "app_a/base.html" %}

{% block content %}

    <p>Topic:  <a href="{% url 'app_a:topic' topic.id %}" >{{topic}}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'app_a:new_entry' topic.id %} " method='post'>
        {% csrf_token %}
        {{ form.as_p}}
        <button name='submit' >Add entry</button>
    </form>


{% endblock content %}

app_a/templates/app_a/new_topic.html
{% extends "app_a/base.html" %}

{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'app_a:new_topic' %}" method='post' >
        {%csrf_token %}
        {{form.as_p}}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

app_a/templates/app_a/sec.html
<head>
  <title>my sec sentence is I will fight back</title> 
  <body>
    <h1>the h1 font is this big?</h1> 
    <h2>and this is h2 font size</h2>
    <h3>of course this is h3</h3>
  </body>
</head>

app_a/templates/app_a/topic.html
{% extends 'app_a/base.html' %}

{% block page_header %}

<h3>Topic: <a href="{% url 'app_a:topic' topic.id %}">{{topic}} </a></h3>
{% endblock page_header %}
{% block content %}
<p>Entries:</p>
<p><a href="{% url 'app_a:new_entry' topic.id %}"> Add new entry</a></p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card_header ">
                <a>   </a>
                {{entry.date_added|date:'M d,Y H:i' }}
            
            <small><a href="{% url 'app_a:edit_entry' entry.id %}">Edit entry </a></small>
            </h4>
            <div class="card-body">
                {{ entry.text| linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}


{% endblock content %}

app_a/templates/app_a/topics.html
{% extends 'app_a/base.html' %}
{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}
{% block content %}


<ul>
    
    {% for topic in topics %}
        <li><h3>
            <a href="{% url 'app_a:topic' topic.id %}">{{topic}}</a></h3>
        </li>

    {% empty %}
        <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
    
</ul>
<h3><a href="{% url 'app_a:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}

app_a/templates/oldindex.html
<!DOCTYPE html>
<html lang='zh-CN'>

<head>
	<meta charset='utf-8'/>
	<title>my first page</title>
</head>

<body>
	<h1>welcome</h1>

</body>

</html>

app_a/templates/oldsec.html
<head>
  <title>my sec sentence is I will fight back</title> 
  <body>
    <h1>the h1 font is this big?</h1> 
    <h2>and this is h2 font size</h2>
    <h3>of course this is h3</h3>
  </body>
</head>

app_b/templates/secfir.html
<title>
    the welcome page in app B
</title>
<body>
    <h1>I think I have already know the structure of django</h1>
    <h2>I'm going to the nexe step</h2>
    <script type="text/JavaScript">
        alert('hello!');

    </script>
</body>